# Generated by Django 5.0.1 on 2024-03-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_expense_expense_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
